### ISSUE TITLE
A program that prints 415

### ISSUE THREAD

**Issue by stasoid** [buttercrab/hyeo-ung-lang#78]
Can you please write a program that prints `415` for me? I would like to add Hyeo-ung to [this polyglot](https://codegolf.stackexchange.com/a/264646), but unable to do so without English docs. I asked ChatGPT, but the programs it produces don't work.

Note: the polyglot already has some Korean characters (`밠밠따빠빠맣박다맣받다맣희맣희`), but Hyeo-ung interpreter doesn't seem to be affected by this. I was able to add the hello world program to the polyglot, and the only change required was to prepend it with `흣`.

**Comment by stasoid** [comment]
@xnuk Maybe you can help me with this?

**Comment by xnuk** [comment]
First, this is a one of the compiler/interpreter repositories, not the actual spec. You can [check the language spec](https://gist.github.com/xnuk/d9f883ede568d97caa158255e4b4d069) and add a comment there, and there's also a [community-maintained compiler/interpreter list](https://github.com/20chan/awesome-hyeong). (Personally I prefer [tirr-c/hyeong-rs](https://github.com/tirr-c/hyeong-rs) interpreter.)

> Note: the polyglot already has some Korean characters (`밠밠따빠빠맣박다맣받다맣희맣희`)

[That Korean characters are 아희 (Aheui)](https://codegolf.stackexchange.com/questions/102370/add-a-language-to-a-polyglot/142382#142382), which 난해한 혀엉... 언어 (Hyeong or Hyeo-ung or whatever) doesn't understand and mostly ignores it. But it understands `.`, `!`, or `?`, and that's why

> I was able to add the hello world program to the polyglot, and the only change required was to prepend it with `흣`.

happens.

> Can you please write a program that prints `415` for me? I would like to add Hyeo-ung to this polyglot, but unable to do so without English docs.

Generally there's 2 ways to achieve this:

1. Put a number `-415` into Stack 1 (stdout)
2. Or put three numbers `52` `49` `53` into there.

And program ends if you pop the Stack 1. I don't want to give a straightforward answer, since I hope you put a language into the polyglot if you understand it. But, I can give a little bit of English overview of the Hyeong language for you:

<details><summary>The little bit</summary>

### Before you read
- The 난해한 혀엉... 언어 (direct translation: Esoteric Hyeong... Language) is frequently referred as a language feels like **moans of gay sex**. I hope you choose the right language.
- 'Hangul', 'Hangul syllable', or 'Korean character' referred in here is a Unicode character in `가`(U+AC00)-`힣`(U+D7A3).

### Instructions
A single instruction starts with Hangul characters, followed by some of dots (`.`), and optionally followed by Unicode heart characters or bangs `!` or question marks `?`. Like `혀엉...` or `혀엉...💗?💕`. Count of Hangul character and count of dots are used like a instruction parameter, and most instructions do more than one thing, by design.

- `형`, `혀엉`, `혀어엉`, `혀어어엉`... : **Push** value of Hangul count * dots count into current stack.
  - ex. `혀어어어엉....` pushes `20` into current stack.
- `항`, `하앙`, `하아앙`, `하아아앙`... : **Pop** *Hangul count* items in current stack, **Sum** of them, **Push** it into Stack *dots count*.
  - ex. `하아아아앙....` pops 5 items, and put the sum into Stack 4.
- `핫`, `하앗`, `하아앗`, `하아아앗`... : Same as above but **Multiple** of them.
  - ex. `하아아아앗....` pops 5 items, and put the multiple into Stack 4.
- `흣`, `흐읏`, `흐으읏`, `흐으으읏`... : **Switch the sign** of top *Hangul count* items in current stack, and **Push the sum** of these items into Stack *dots count*.
  - ex. If stack is `1 0 -3 4` and `4` is a topmost item, `흐읏...` makes the stack `1 0 3 -4`, and pushes `-1` into Stack 3.
  - The 'switch' behavior is treated as pop then push.
- `흡`, `흐읍`, `흐으읍`, `흐으으읍`... : **Invert fractions** of top *Hangul count* items in current stack, and **Push the multiple** of these items into Stack *dots count*.
  - ex. If stack is `1 6 (-3/2) (4/7)` and `4/7` is a topmost item, `흐으읍...` makes the stack `1 (1/6) (-2/3) (7/4)`, and pushes `-7/36` into Stack 3.
  - Invert of `0` is `NaN`.
  - The 'invert' behavior is treated as pop then push.
- `흑`, `흐윽`, `흐으윽`, `흐으으윽`... : **Pop one item** from current stack, and **Duplicate**s it and push *Hangul count* items of it into Stack *dots count*, and **Push one again**, and **Switch to** Stack *dots count*.
  - ex. `흐윽....` pushes a topmost item of current stack into Stack 2 by 4 times, and switches stack pointer to Stack 4.

### Stack
- A program runtime has many stacks.
- Every stack items are rational numbers, or `NaN`.
- Stack 0 is stdin.
  - Popping empty stack reads and stores input as Unicode characters.
  - Behaves like normal stack for push or non-empty pop.
- Stack 1 is stdout.
  - Always empty, so strictly this is not a stack.
  - Pushing a non-negative integer prints corresponding Unicode character.
  - Pushing negative integer prints number with ASCII decimal digits, excluding a minus sign.
  - Pushing fractions are treated as integers by rounding down.
  - Pushing a `NaN` prints `너무 커엇...`.
  - Popping this stack ends program successfully.
- Stack 2 is same as Stack 1, except:
  - It prints into stderr
  - Popping this stack ends program, but unsuccessfully.
- From Stack 3 and later, these are just normal stack.
  - Popping empty stack generates `NaN`
  - Stack 3 is selected by default on program start.

### etc
- Every uninterpretable characters are just ignored, like alphanumerics, whitespaces, or even Hangul outside of instructions.
  - For example, this means `혀어 엉 어어 . 앗 .` is a valid instruction: push 3 * 2 = 6 in current stack.
- Feel free to ask me question related to this.

</details>

**Comment by stasoid** [comment]
@xnuk Wow, that's a very comprehensive answer, thanks a lot.
I wasn't aware of the interpreter list, thank you.
I was aware of the spec, but was unable to understand the automatic translation of it. Now, with your translation, I will finally be able to write the program.
